/**
 * Audit action codes, said the way a person would say them.
 *
 * The stored codes (`cycle.skipped`, `private_response.created`) belong to the
 * domain and must not change: they go into an append-only table and are queried
 * by value. This map lives at the UI boundary so a teacher reading the history
 * sees what happened instead of an implementation identifier.
 *
 * An unmapped code falls back to a de-underscored sentence-case form, so a new
 * action added later reads plainly rather than breaking.
 */
const LABELS: Record<string, string> = {
  "cycle.generated": "Weeks generated",
  "cycle.opened": "Week opened",
  "cycle.closed": "Week closed",
  "cycle.reopened": "Week reopened",
  "cycle.skipped": "Week skipped",
  "cycle.restored": "Week restored",
  "cycle.window_overridden": "Week dates changed",
  "recurrence.configured": "Weekly schedule saved",
  "response.submitted": "Form submitted",
  "response.edited": "Form edited",
  "response.draft_saved": "Draft saved",
  "response.locked": "Form locked",
  "response.unlocked": "Form unlocked",
  "response.item_withdrawn": "Question withdrawn by the student",
  "response.review_state_changed": "Review state changed",
  "response.validity_changed": "Participation credit changed",
  "item.review_state_changed": "Question review state changed",
  "item.type_category_corrected": "Question type or topic corrected",
  "validity.flagged": "Submission flagged",
  "validity.flag_confirmed": "Flag confirmed, credit removed",
  "validity.flag_rejected": "Flag dismissed, credit kept",
  "validity.invalidated": "Participation credit removed",
  "validity.restored": "Participation credit restored",
  "private_response.created": "Private reply sent",
  "private_response.removed": "Private reply removed",
  "private_response.student_follow_up": "Student replied privately",
  "public_answer.drafted": "Public answer drafted",
  "public_answer.edited": "Public answer edited",
  "public_answer.revised": "Public answer revised",
  "public_answer.reworded": "Public question reworded",
  "public_answer.scheduled": "Publication scheduled",
  "public_answer.schedule_cancelled": "Publication schedule cancelled",
  "public_answer.published": "Published to the section",
  "public_answer.publish_failed": "Publication failed",
  "public_answer.unpublished": "Public answer unpublished",
  "public_answer.restored": "Public answer restored",
  "public_answer.approved": "Public answer approved",
  "public_answer.rejected": "Public answer rejected",
  "public_answer.submitted_for_approval": "Public answer sent for approval",
  "source_link.created": "Answer linked to its source submission",
  "merge.created": "Questions merged",
  "merge.member_added": "Question added to a merge",
  "merge.member_removed": "Question removed from a merge",
  "merge.unmerged": "Merge undone",
  "match.candidates_generated": "Account matches suggested",
  "match.confirmed": "Account match confirmed",
  "match.rejected": "Account match rejected",
  "match.unlinked": "Account unlinked",
  "match.corrected": "Account match corrected",
  "match.correction_started": "Account match correction started",
  "claim.submitted": "Link request received",
  "claim.confirmed": "Link request confirmed",
  "claim.rejected": "Link request rejected",
  "claim.auto_confirmed": "Link request confirmed automatically",
  "student_number.revealed": "Student number revealed",
  "student_number.backfilled": "Student numbers backfilled",
  "student_record.name_corrected": "Student name corrected",
  "student_record.fields_updated": "Student details updated",
  "roster.parsed": "Class list read",
  "roster.preview_edited": "Class list preview edited",
  "roster.imported": "Class list imported",
  "legacy.staged": "Earlier questions staged",
  "legacy.committed": "Earlier questions imported",
  "legacy.imported": "Earlier questions imported",
  "legacy.row_updated": "Earlier question edited",
  "legacy.identity_preservation_changed": "Earlier-question identity setting changed",
  "section.created": "Section created",
  "section.updated": "Section settings updated",
  "course.created": "Course created",
  "course.updated": "Course settings updated",
  "course.archived": "Course archived",
  "course.restored": "Course restored",
  "course.cloned": "Course copied",
  "staff.assigned": "Staff member added",
  "staff.removed": "Staff member removed",
  "staff.permissions_changed": "Staff permissions changed",
  "template.created": "Template created",
  "template.version_created": "Template version saved",
  "user.teacher_role_changed": "Teacher role changed",
  "participation.exported": "Participation export downloaded",
  "export.responses": "Responses export downloaded",
  "export.bonus_records": "Bonus records export downloaded",
  "export.backlog_status": "Backlog status export downloaded",
  "export.pdf_summary": "Summary PDF downloaded",
  "backlog.question_created": "Backlog question added",
  "backlog.copied_from_submission": "Question copied to the backlog",
  "backlog.moved_from_submission": "Question moved to the backlog",
  "backlog.state_changed": "Backlog question updated",
  "backlog.metadata_updated": "Backlog question details updated",
  "backlog.assigned": "Backlog question assigned",
  "backlog.made_visible_to_section": "Backlog question shared with a section",
  "backlog.draft_answer_saved": "Backlog draft answer saved",
  "backlog.recommended": "Backlog change recommended",
  "backlog.recommendation_approved": "Backlog recommendation approved",
  "backlog.recommendation_rejected": "Backlog recommendation rejected",
  "backlog.recommendation_withdrawn": "Backlog recommendation withdrawn",
  "triage.will_answer": "Marked to answer",
  "triage.will_not_answer": "Marked not to answer",
  "triage.will_not_answer_undone": "Not-answering decision undone",
  "bonus_period.created": "Bonus period created",
  "bonus_period.updated": "Bonus period updated",
  "bonus_period.archived": "Bonus period archived",
  "bonus_period.default_changed": "Default bonus period changed",
  "analysis.note_created": "Staff note added",
  "analysis.note_updated": "Staff note edited",
  "analysis.note_archived": "Staff note archived",
  "comment.submitted": "Comment posted",
  "comment.moderated": "Comment moderated",
  "discussion.lock_changed": "Discussion lock changed",
  "email.queued": "Email queued",
  "email.sent": "Email sent",
  "email.failed": "Email failed",
};

export function auditActionLabel(action: string): string {
  const known = LABELS[action];
  if (known) return known;
  const words = action.replace(/[._]/g, " ").trim();
  return words.charAt(0).toUpperCase() + words.slice(1);
}
